import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import "bootstrap/dist/css/bootstrap.min.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

//0. Install dependencies DONE
//1. Import dependencies //DONE
//2. Setup references and state hooks //DONE
//3. Load Tensorflow Model //DONE
//4. Handle Questions //DONE
//5. Setup input , question and results area //DONE
